config/routes.rb
Rails.application.routes.draw do

  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]

  root to: 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord

    has_many :departing_flights, foreign_key: 'departure_airport', class_name: 'Flight'
    has_many :arriving_flights, foreign_key: 'arrival_airport', class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passengers, dependent: :destroy

    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    
    belongs_to :departing_airport, class_name: 'Airport', foreign_key: 'departure_airport'
    belongs_to :arriving_airport, class_name: 'Airport', foreign_key: 'arrival_airport'
    has_many :bookings

    def self.user_search(query_params)
        where(departure_airport: query_params[:origin_id],
              arrival_airport: query_params[:dest_id],
              departure_date: query_params[:flight_date])
    end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        redirect_to :root and return unless search?

        @booking = Booking.new
        @num_of_passengers = params[:tickets]
        @num_of_passengers.to_i.times { @booking.passengers.build}
        @flight = Flight.find_by(id: params[:flight_id])
        @departure_airport = @flight.departing_airport.code
        @arrival_airport = @flight.arriving_airport.code
        @flight_date = @flight.departure_date.strftime('%B %d, %Y')
    end

    def create
        @booking = Booking.new(booking_params)

        if @booking.save
            redirect_to @booking and return
        end
        render :new, status: :unprocessable_entity
    end

    def show
        @booking = Booking.find(params[:id])

    end

    private
    def booking_params
        params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end

    def search?
        return true if params[:commit] == 'Book'
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

    def index
        @flights = Flight.all
        @dates = Flight.select(:departure_date).distinct
        @origin_airport = Airport.find_by(id: params[:origin_id])
        @arrival_airport = Airport.find_by(id: params[:dest_id])
        @flight_date = params[:flight_date]
        @available_flights = Flight.user_search(query_params)
    end

    private
    def query_params
        params.permit(:origin_id, :dest_id, :flight_date, :tickets)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Book Flight</h1>

<%= form_with model: @booking do |f| %>
    <h2>Booking a flight to <%= @arrival_airport %> from <%= @departure_airport %> on <%= @flight_date %></h2>
    <%= f.hidden_field(:flight_id, value: @flight.id)%>
    <%= f.fields_for :passengers do |sub_form| %>
        <h4>Passenger Information</h4>
        <%= sub_form.label(:name)%>
        <%= sub_form.text_field(:name) %>
        
        <%= sub_form.label(:email)%>
        <%= sub_form.text_field(:email) %>
    <% end %>
    <div>
        <%= f.submit 'Purchase Flight'%>
    </div>
<% end %>

app/views/bookings/show.html.erb
<h1>Your booked flight on <%= @booking.flight.departure_date.strftime('%B %d, %Y') %></h1>

<h2>Departure: <%= @booking.flight.departure_time %>
<h2>From <%= @booking.flight.departing_airport.code %> to <%= @booking.flight.arriving_airport.code %></h2>

<h3> <%= @booking.passengers.count %> Passengers</h3>
<% @booking.passengers.each do |p| %>
    <div>
        <p>Name: <%= p.name %><p>
        <p>Email: <%= p.email %></p>
    <div>
<% end %>

app/views/flights/index.html.erb
<h1>Flight Finder</h1>

<%= form_with model: @flight, method: :get do |f| %>
    <%= f.collection_select(:origin_id, Airport.all.order(:code), :id, :code, prompt: 'Origin') %>
    <%= f.collection_select(:dest_id, Airport.all.order(:code), :id, :code, prompt: 'Destination') %>    
    <%= f.collection_select(:flight_date, @dates, :departure_date, :departure_date, prompt: 'Date of Departure') %>
    <%= f.select(:tickets, 1..4, prompt: 'Num of Tickets') %>
    <%= f.submit 'Search' %>
<% end %>

<%# Display all available flights, if there any %>
<%# Otherwise display "No flights available" %>
<% if @available_flights.present? %>
    <h4><%= pluralize(@available_flights.count, 'flight') %> available from <%= @origin_airport.code %> to <%= @arrival_airport.code %> on <%= @flight_date.to_date.strftime('%B %d, %Y') %></h4>
    <%= form_with model: @flight, method: :get, url: new_booking_path do |f| %>
        <%= f.collection_radio_buttons(:flight_id, @available_flights, :id, :departure_time, required: true)%>
        <%= f.hidden_field('tickets', value: params[:tickets]) %>
        <%= f.submit 'Book' %>
    <% end %>
<% else %>
    <h3>No available flights on the specified date</h3>
    <h3>Please select a new date</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>